{
    'name':"Recurring Subscription ",
    'author':'odoo',
    'version':'17.0.6.0',
    'category':'reccuring',
    'summary':'Subscription',
    'depends':['base',
               'product',
               'contacts',
               'crm',
               'account',
               'base_automation',
               ],
    'license': 'GPL-2',
    'sequence':-104,
    'installation': True,
    'application': True,
    'data':[
        'security/res_groups.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',
        'data/ir_actions_server_data.xml',
        'data/automatic_action.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/seq_recurring_subscription.xml',
        'data/product_data.xml',
        'views/recurring_subscription_views.xml',
        'views/recurring_credit_views.xml',
        'views/billing_schedule_views.xml',
        'views/partner_account_id_views.xml',
        'views/res_partner_views.xml',
        'views/crm_lead_views.xml',
        ],
}